services:
  - type: web
    name: pdf-image-converter
    env: python
    plan: free
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-hin poppler-utils
      pip install -r requirements.txt
    startCommand: gunicorn app:app --timeout 120