services:
  - type: web
    name: pdf-image-converter
    env: python
    plan: free
    healthCheckPath: /
    
    preBuildCommand: "fallocate -l 1G /swapfile && chmod 600 /swapfile && mkswap /swapfile && swapon /swapfile"
    
    buildCommand: |
      apt-get update && apt-get install -y tesseract-ocr tesseract-ocr-hin poppler-utils
      pip install -r requirements.txt
      
    # --- ★★★ सबसे सरल स्टार्ट कमांड ★★★ ---
    startCommand: gunicorn app:app
